language: java
sudo: false
install: gradle wrapper --gradle-version 4.5

before_script:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - oraclejdk8
  - openjdk8
